app/__init__.py
# coding: utf-8
import traceback
import logging
from logging.handlers import TimedRotatingFileHandler

from flask import Flask, g
from flask.ext.bootstrap import Bootstrap
from flask.ext.moment import Moment
from flask.ext.assets import Bundle, Environment

from config import config

bootstrap = Bootstrap()
moment = Moment()

# assets = Environment()

# bundles = {
#     }
# assets.register(bundles)


def create_app(config_name):
    try:
        app = Flask(__name__)
        app.config.from_object(config[config_name])
        config[config_name].init_app(app)
        # init the logging handler
        init_logging_handler(app)
        # init the add-ons
        bootstrap.init_app(app)
        moment.init_app(app)
        # assets.init_app(app)

        # register the blueprint
        from .main import main as main_blueprint
        app.register_blueprint(main_blueprint, url_prefix='/job_analysis')
    except Exception, e:
        print traceback.format_exc()

    return app


def init_logging_handler(app):
    handler = TimedRotatingFileHandler(app.config['LOGGING_LOCATION'], when='MIDNIGHT')
    handler.setLevel(app.config['LOGGING_LEVEL'])
    formatter = logging.Formatter(app.config['LOGGING_FORMAT'])
    handler.setFormatter(formatter)
    app.logger.addHandler(handler)

app/main/__init__.py
# coding: utf-8
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
# coding: utf-8
from . import main
from flask import render_template, jsonify, flash, request, current_app, url_for, Response, g, abort


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/about')
def about_page():
    return render_template('about.html')

app/templates/about.html
{% extends "layout.html" %}

{% block title %}什么值得做 - 关于{% endblock %}

{% block page_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-1">
            <h2 class="page-header">
                关于
            </h2>
            <p>一个通过数据分析互联网工作情况的网站。每两周更新一次。</p>
            <p>主要信息来源：<a href="">拉勾网</a></p>
            <h3>Powered by</h3>
            <table class="table table-striped table-hover ">
              <tbody>
                <tr style="margin-bottom: 10px">
                  <td><a href="">Flask</a> + <a href="">gunicorn</a> + <a href="">nginx</a></td>
                  <td>web server</td>
                </tr>
                <tr>
                  <td><a href="">C3.js</a></td>
                  <td>图表绘制</td>
                </tr>
                <tr>
                  <td><a href="">scrapy</a></td>
                  <td>开源 python 爬虫框架</td>
                </tr>
                <tr>
                  <td><a href="">d3-cloud</a></td>
                  <td>标签云绘制</td>
                </tr>
                <tr>
                  <td><a href="">Bootstrap</a></td>
                  <td>Twitter 的前端框架</td>
                </tr>
              </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <link href="//cdn.bootcss.com/c3/0.4.11/c3.css" rel="stylesheet">
<style>

</style>
{% endblock %}

{% block title %}什么值得做{% endblock %}

{% block page_content %}
<div class="container">
  <div class="row">
    <div class="python-jumbotron jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <img src="{{url_for('static', filename='img/python-logo.png')}}" alt="python_logo">
          </div>
          <div class="col-lg-8">
            <p style="color: #e6e8ea">
              python 在拉勾上的职位共有3934个，以下是 python 岗位的有关数据。由于使用的关键字为“Python”或“python”，可能会遗漏某些未使用该关键字但是与 python 相关的岗位。
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12" id='tech_keywords'>
        <h2 class="col-lg-12 chart-title">最常见的技术关键词<a class="anchor" href="#tech_keywords"> ¶</a></h2>
      <div class="col-lg-6">
        <div id="keywords_stats"></div>
      </div>
      <div class="col-lg-6">
        <div id="keywords_cloud"></div>
      </div>
      <div class="col-lg-12">
        <p>
          柱状图与标签云来自于同一组数据。柱状图中，纵轴为该关键词在岗位描述中出现的次数。在标签云中，你可以更直观地看出，python 的岗位还是以服务器端开发为主，并且 django 及 mysql 的热度远超其他。并且前端 html/css/javascript 出现的频率比我想象的更高，姑且认为在使用 python 的部分公司中，前端知识也是不可或缺的。
        </p>
      </div>
    </div>

    <div class="col-lg-12" id="salary_avg">
        <h2 class="col-lg-12 chart-title">薪资平均数分布<a class="anchor" href="#salary_avg"> ¶</a></h2>
      <div class="col-lg-8">
        <div id="salary_pie_chart"></div>
      </div>
      <div class="col-lg-4">
        <p>
          薪资的统计规则如下：
          <div class="alert alert-success" role="alert">
            <p>当薪资范围为闭区间时，取平均整数。例如8-16k，则平均值为12k。</p>
            <p>当薪资范围是半开区间，例如“30k 以上”，则取最小值30k。</p>
          </div>
          可以看出超过三分之一的薪资均值落在11-15k 区间内，然后就是6-10k和16-20k 的区间。我知道脱离地区来谈薪资都是耍流氓，我会在后面加上地域筛选的 :)
        </p>
      </div>

    </div>
    <div class="col-lg-12" id="exp_requirement">
        <h2 class="col-lg-12 chart-title">经验要求是什么<a class="anchor" href="#exp_requirement"> ¶</a></h2>
      <div class="col-lg-8">
        <div id="experience_pie_chart"></div>
      </div>
      <div class="col-lg-4">
        <p>
          不知道是好事还是坏事，半数以上的公司都需要1-3年经验的 python 开发者。我还没有统计过其他语言的情况，并没有发言权。但是这是不是意味着使用 python 的公司会在度过冷启动阶段之后，就切换到了其他语言呢？目前不得而知，但是我们会弄清楚的。
        </p>
      </div>

    </div>
    <div class="col-lg-12" id="location_requirement">
        <h2 class="col-lg-12 chart-title">哪些地区需求最旺盛<a class="anchor" href="#location_requirement"> ¶</a></h2>
      <div class="col-lg-8">
        <div id="location_pie_chart"></div>
      </div>
      <div class="col-lg-4">
        <p>
          接近半数的岗位都集中在帝都，果然是名不虚传。而这已经是提供的岗位超过30个的所有城市了。只能说 python 在国内的应用场景可能还是太少。不知道随着时间的推移，我们能否看到 python 在国内有一个更光明的未来。
        </p>
      </div>

    </div>
    <div class="col-lg-12" id="degree_requirement">
        <h2 class="col-lg-12 chart-title">学历要求分布<a class="anchor" href="#degree_requirement"> ¶</a></h2>
      <div class="col-lg-8">
        <div id="degree_pie_chart"></div>
      </div>
      <div class="col-lg-4">
        <p>
          学历依然是敲门砖，只有不到五分之一的职位不要求学历。
        </p>
      </div>

    </div>
    <div class="col-lg-12" id="job_type">
        <h2 class="col-lg-12 chart-title">工作类型分布<a class="anchor" href="#job_type"> ¶</a></h2>
      <div class="col-lg-8">
        <div id="type_pie_chart"></div>
      </div>
      <div class="col-lg-4">
        <p>
          数据有一定局限性，在拉勾上很少有实习或者兼职招聘。
        </p>
      </div>

    </div>

    <div class="col-lg-12">
    <hr>
      <h2>Comments</h2>
      <div id="disqus_thread"></div>
        <script>
            var disqus_config = function () {
                this.page.url = '{{ url_for("main.index", _external=True) }}';  // Replace PAGE_URL with your page's canonical URL variable
                this.page.identifier = 'python'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
            };

            (function() {  // DON'T EDIT BELOW THIS LINE
                var d = document, s = d.createElement('script');

                s.src = '//jobanalysis.disqus.com/embed.js';

                s.setAttribute('data-timestamp', +new Date());
                (d.head || d.body).appendChild(s);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
    </div>
  </div>
</div>

{% endblock %}


{% block scripts %}
  {{super()}}
  <script type="text/javascript" src="//cdn.bootcss.com/d3/3.5.17/d3.min.js"></script>
  <script type="text/javascript" src="//cdn.bootcss.com/c3/0.4.11/c3.min.js"></script>
  <script type="text/javascript" src={{url_for('static', filename='js/stats.js')}}></script>
  <script type="text/javascript" src={{url_for('static', filename='js/d3.layout.cloud.js')}}></script>
  <script>
    plot_keywords('{{url_for('static', filename='data/keywords_stats.json')}}', '#keywords_stats');
    plot_pie_chart('{{url_for('static', filename='data/experience.json')}}', '#experience_pie_chart');
    plot_pie_chart('{{url_for('static', filename='data/location.json')}}', '#location_pie_chart');
    plot_pie_chart('{{url_for('static', filename='data/degree.json')}}', '#degree_pie_chart');
    plot_pie_chart('{{url_for('static', filename='data/type.json')}}', '#type_pie_chart');
    plot_pie_chart('{{url_for('static', filename='data/salary.json')}}', '#salary_pie_chart');
    plot_keywords_cloud('{{url_for('static', filename='data/keywords_cloud.json')}}', '#keywords_cloud');
  </script>

{% endblock %}

app/templates/layout.html
{% extends "bootstrap/base.html" %}

{% block head %}
<link rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}">
{{super()}}
<link rel="icon" href="{{url_for('static', filename='img/favicon.ico')}}" type="image/x-icon" />
<link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.ico')}}" type="image/x-icon" />
<link rel="apple-touch-icon" href="{{url_for('static', filename='img/favicon.png')}}" sizes="57x57" />
{% endblock %}

{% block title %}什么值得做{% endblock %}

{% block body %}
<div id='wrap'>
{% block navbar %}
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle"
        data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('main.index') }}">什么值得做</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('main.index') }}">Python</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li><a href="{{ url_for('main.about_page') }}">关于</a></li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
  {% block msg_content %}
    <div class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      {% if category == 'message' %}
      <div class="alert alert-warning">
        <button class="close" type="button" data-dismiss="alert">&times;</button>
        {{ message|safe }}
      </div>
      {% else %}
      <div class="alert {{ category }}">
        <button class="close" type="button" data-dismiss="alert">&times;</button>
        {{ message|safe }}
      </div>
      {% endif %}
      {% endfor %}
      {% endif %}
      {% endwith %}
    </div>
  {% endblock %}
<a href="https://github.com/namco1992/job_analysis"><img style="position: absolute; top: 0; left: 0; border: 0; z-index: 999;" src="https://camo.githubusercontent.com/567c3a48d796e2fc06ea80409cc9dd82bf714434/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_darkblue_121621.png"></a>
  {% block page_content %}
  {% endblock %}
  <div id="push"></div>
{% endblock %}
<!-- footer begin -->
</div>
  <div id="footer">
      <div class="container">
        <div class="text-center">
          <p class="text-muted" style="margin-top: 20px">Copyright © 2016 All rights reserved. </p>
          <p><a href="https://github.com/namco1992/job_analysis/issues">Have Issues?</a></p>
        </div>
      </div>
  </div>

  {% block scripts %}
    {{ super() }}
  {% endblock %}
{% endblock %}